# Generated by Django 6.0.3 on 2026-04-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0002_alter_globalsetting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
