# Generated by Django 6.0.3 on 2026-03-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_retakes',
            field=models.PositiveIntegerField(default=3, help_text='Max number of allowed retakes'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit_mins',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes'),
        ),
    ]
