# Generated by Django 6.0.3 on 2026-03-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_text',
            field=models.TextField(blank=True, help_text='Direct text submission', null=True),
        ),
    ]
