# Generated by Django 6.0.3 on 2026-07-31 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0014_remove_courseenrollment_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('paused', 'Paused'), ('submitted', 'Submitted'), ('evaluated', 'Evaluated'), ('terminated', 'Terminated')], default='started', max_length=20)),
                ('total_score', models.PositiveIntegerField(blank=True, null=True)),
                ('total_violations', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('code', 'Code')], default='text', max_length=10)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('order_number', models.PositiveIntegerField(default=0)),
                ('max_words', models.PositiveIntegerField(blank=True, null=True)),
                ('programming_language', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('pdf_source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='exams.examattempt')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_required', models.BooleanField(default=False)),
                ('microphone_required', models.BooleanField(default=False)),
                ('fullscreen_required', models.BooleanField(default=False)),
                ('copy_protection', models.BooleanField(default=False)),
                ('allow_resume', models.BooleanField(default=True)),
                ('allow_back_navigation', models.BooleanField(default=True)),
                ('show_result_after_publish', models.BooleanField(default=True)),
                ('snapshot_mode', models.CharField(choices=[('every_question', 'Every Question'), ('every_n_questions', 'Every N Questions'), ('random', 'Random'), ('custom', 'Custom')], default='every_question', max_length=20)),
                ('snapshot_interval', models.PositiveIntegerField(blank=True, help_text='Interval parameter depending on mode', null=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='exams.examattempt')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='exams.examquestion')),
            ],
            options={
                'ordering': ['captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('COPY_ATTEMPT', 'Copy Attempt'), ('PASTE_ATTEMPT', 'Paste Attempt'), ('RIGHT_CLICK', 'Right Click'), ('CAMERA_OFF', 'Camera Off'), ('MICROPHONE_OFF', 'Microphone Off'), ('FULLSCREEN_EXIT', 'Fullscreen Exit')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='exams.examattempt')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='exams.examquestion')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('code_answer', models.TextField(blank=True, null=True)),
                ('marks_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('instructor_feedback', models.TextField(blank=True, null=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_saved', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
