# Generated by Django 6.0.3 on 2026-07-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('paused', 'Paused'), ('submitted', 'Submitted'), ('evaluated', 'Evaluated'), ('terminated', 'Terminated')], db_index=True, default='started', max_length=20),
        ),
    ]
