# Generated by Django 6.0.3 on 2026-07-31 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_status_alter_examattempt_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamImportMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('import_source', models.CharField(default='PDF', max_length=50)),
                ('extraction_version', models.CharField(default='1.0', max_length=20)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_metadata', to='exams.exam')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
