# Generated by Django 6.0.3 on 2026-07-31 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examimportmetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examanswer',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='examanswer',
            name='code_answer',
        ),
        migrations.RemoveField(
            model_name='examanswer',
            name='last_saved_at',
        ),
        migrations.RemoveField(
            model_name='examanswer',
            name='text_answer',
        ),
        migrations.RemoveField(
            model_name='examanswer',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='ai_generated',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='pdf_source_page',
        ),
        migrations.AddField(
            model_name='examanswer',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='exam_audio/'),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='code_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='transcript_status',
            field=models.CharField(default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='transcript_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='max_recording_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='starter_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='transcript_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='order_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(default='text', max_length=50),
        ),
    ]
