# Generated by Django 6.0.3 on 2026-07-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_examanswer_audio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsettings',
            name='auto_terminate_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsettings',
            name='max_warnings',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='examviolation',
            name='severity',
            field=models.CharField(default='Low', max_length=20),
        ),
    ]
