# Generated by Django 6.0.3 on 2026-08-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_assign_to_all_enrolled_examassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='examimportmetadata',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examimportmetadata',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='examviolation',
            name='violation_type',
            field=models.CharField(choices=[('TAB_HIDDEN', 'Tab Hidden'), ('TAB_RETURNED', 'Tab Returned'), ('WINDOW_BLUR', 'Window Blur'), ('WINDOW_FOCUS', 'Window Focus'), ('TAB_SWITCH', 'Tab Switch (Legacy)'), ('COPY_ATTEMPT', 'Copy Attempt'), ('PASTE_ATTEMPT', 'Paste Attempt'), ('RIGHT_CLICK', 'Right Click'), ('CAMERA_OFF', 'Camera Off'), ('MICROPHONE_OFF', 'Microphone Off'), ('FULLSCREEN_EXIT', 'Fullscreen Exit')], max_length=20),
        ),
    ]
