# Generated by Django 6.0.3 on 2026-08-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_examimportmetadata_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsettings',
            name='snapshot_custom_questions',
            field=models.CharField(blank=True, help_text='Comma-separated question numbers for custom mode', max_length=255, null=True),
        ),
    ]
