# Generated by Django 6.0.3 on 2026-03-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_announcement_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('link', 'External Link'), ('drive', 'Google Drive'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo')], default='link', max_length=20),
        ),
    ]
