# Generated by Django 6.0.3 on 2026-03-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/attachments/'),
        ),
    ]
