# Generated by Django 6.0.3 on 2026-03-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='pending', max_length=20),
        ),
    ]
