# Generated by Django 6.0.3 on 2026-07-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_enrollmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(default='enrolled', max_length=20),
        ),
    ]
