# Generated by Django 6.0.3 on 2026-07-27 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_courseenrollment_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='status',
        ),
    ]
