# Generated by Django 6.0.3 on 2026-03-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_joined_at_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('under_review', 'Under Review')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
